// src/components/EditorLists.vue
<template>
  <div id="editor-lists">
    <div class="column">
      <list :items="peerTeachers" @selection-changed="handlePtClick" #default="pt">
        {{ pt.item.name }} <button @click.stop="deletePeerTeacher(pt.item.id)">X</button>
      </list>
    </div>
    <div class="column">
      <list :items="compatibleLabs" #default="lab">
        {{ lab.item.fullInfo }} <button @click.stop="assignLab(lab.item.id)">+</button>
      </list>
    </div>
    <div class="column">
      <list :items="selectedPeerTeacherAssignments" #default="lab">
        {{ lab.item.fullInfo }} <button @click.stop="unassignLab(lab.item.id)">X</button>
      </list>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';
import List from '@/components/List.vue';
import PeerTeacher from '@/models/PeerTeacher';
import Lab from '@/models/Lab';

export default defineComponent({
  name: 'EditorLists',
  components: {
    List,
  },
  props: {
    peerTeachers: {
      type: Array as PropType<PeerTeacher[]>,
      default: [],
    },
    labs: {
      type: Array as PropType<Lab[]>,
      default: [],
    },
  },
  computed: {
    compatibleLabs(): Lab[] {
      const temp = this.labs.filter((lab) => (!this.selectedPeerTeacher.assignedLabs.has(lab.id)
        && !this.selectedPeerTeacher.conflictsWith(lab.event)));

      const currentAssignments = this.selectedPeerTeacherAssignments;
      return temp.filter((lab) => !currentAssignments
        .some((assignedLab) => lab.event.conflictsWith(assignedLab.event)));
    },
    selectedPeerTeacherAssignments(): Lab[] {
      return Array.from(this.selectedPeerTeacher.assignedLabs.values())
        .flatMap((id) => {
          const lab = this.$store.state.labs.get(id);
          return (lab === undefined) ? [] : [lab];
        }).sort((a, b) => a.course - b.course || a.section - b.section);
    },
  },
  data() {
    return {
      selectedPeerTeacher: new PeerTeacher(),
    };
  },
  methods: {
    handlePtClick(peerTeacher: PeerTeacher) {
      this.selectedPeerTeacher = peerTeacher;
    },
    deletePeerTeacher(id: number) {
      if (this.selectedPeerTeacher.id === id) {
        this.selectedPeerTeacher = new PeerTeacher();
      }
      this.$store.commit('deletePeerTeacher', id);
    },
    assignLab(id: string) {
      if (this.selectedPeerTeacher.id !== 0) {
        this.selectedPeerTeacher.assignedLabs.add(id);
      }
    },
    unassignLab(id: string) {
      this.selectedPeerTeacher.assignedLabs.delete(id);
    },
  },
});
</script>

<style>
#editor-lists {
  display: flex;
  max-height: inherit;
  min-height: 0;
}

.column {
  flex: 1;
  overflow: auto;
}
</style>

// src/components/EditorLists.svelte
<script lang="ts">
  import IconButton from "@smui/icon-button";
  import List, {
    Item,
    Meta,
    PrimaryText,
    SecondaryText,
    Text,
  } from "@smui/list";
  import type PeerTeacher from "../models/PeerTeacher";
  import { labStore, ptStore } from "../stores";

  let selectedPeerTeacher: PeerTeacher | undefined;

  $: peerTeachers = [...$ptStore.values()].sort((a, b) =>
    a.lastname.toUpperCase() === b.lastname.toUpperCase()
      ? a.firstname.toUpperCase().localeCompare(b.firstname.toUpperCase())
      : a.lastname.toUpperCase().localeCompare(b.lastname.toUpperCase())
  );

  $: labs = [...$labStore.values()].sort((a, b) => a.id - b.id);

  $: assignedLabs = [...(selectedPeerTeacher?.labs.values() ?? [])]
    .flatMap((labId) => {
      const lab = $labStore.get(labId);
      return lab === undefined ? [] : [lab];
    })
    .sort((a, b) => a.id - b.id);

  $: compatibleLabs = labs.filter(
    (lab) =>
      !selectedPeerTeacher?.labs.has(lab.id) &&
      !selectedPeerTeacher?.conflictsWith(lab.event) &&
      !assignedLabs.some((assignment) =>
        assignment.event.conflictsWith(lab.event)
      )
  );

  function deletePT(id: number) {
    if (selectedPeerTeacher?.id === id) {
      selectedPeerTeacher = undefined;
    }

    ptStore.update((val) => {
      val.delete(id);
      return val;
    });
  }

  function assignLab(id: number) {
    selectedPeerTeacher?.labs.add(id);
    // Self assignemnt to update `assignedLabs` and `compatibleLabs`
    selectedPeerTeacher = selectedPeerTeacher;
  }

  function unassignLab(id: number) {
    selectedPeerTeacher?.labs.delete(id);
    // Self assignemnt to update `assignedLabs` and `compatibleLabs`
    selectedPeerTeacher = selectedPeerTeacher;
  }
</script>

<div id="editor-lists">
  <div class="column">
    <h3 class="col-header">Peer Teachers</h3>
    <List twoLine singleSelection class="editor-list">
      {#each peerTeachers as pt}
        <Item on:SMUI:action={() => (selectedPeerTeacher = pt)}>
          <Text>
            <PrimaryText>{pt.name}</PrimaryText>
            <SecondaryText>{pt.id}</SecondaryText>
          </Text>
          <Meta>
            <IconButton
              class="material-icons"
              on:click$stopPropagation={() => {
                deletePT(pt.id);
              }}
            >
              remove_circle
            </IconButton>
          </Meta>
        </Item>
      {/each}
    </List>
  </div>
  <div class="column">
    <h3 class="col-header">Labs</h3>
    <List threeLine class="editor-list">
      {#each compatibleLabs as lab}
        <Item>
          <Text>
            <PrimaryText>{lab.course}-{lab.section}</PrimaryText>
            <SecondaryText>{lab.time}</SecondaryText>
            <SecondaryText>{lab.location}</SecondaryText>
          </Text>
          <Meta class="material-icons">
            <IconButton
              class="material-icons"
              on:click$stopPropagation={() => {
                assignLab(lab.id);
              }}
            >
              add_circle
            </IconButton>
          </Meta>
        </Item>
      {/each}
    </List>
  </div>
  <div class="column">
    <h3 class="col-header">
      {selectedPeerTeacher?.name ?? "PT"} - Assigned Labs
    </h3>
    <List threeLine class="editor-list">
      {#each assignedLabs as lab}
        <Item>
          <Text>
            <PrimaryText>{lab.course}-{lab.section}</PrimaryText>
            <SecondaryText>{lab.time}</SecondaryText>
            <SecondaryText>{lab.location}</SecondaryText>
          </Text>
          <Meta class="material-icons">
            <IconButton
              class="material-icons"
              on:click$stopPropagation={() => {
                unassignLab(lab.id);
              }}
            >
              remove_circle
            </IconButton>
          </Meta>
        </Item>
      {/each}
    </List>
  </div>
</div>

<style>
  #editor-lists {
    display: flex;
    max-height: inherit;
    min-height: 0;
    overflow-x: auto;
  }

  .col-header {
    font-family: Roboto, sans-serif;
  }

  .column {
    flex: 1;
    min-width: 15em;
    overflow: auto;
  }

  * :global(.editor-list) {
    border: 1px solid black;
  }
</style>
