// src/views/Editor.vue
<template>
  <div id="editor">
    <ActionBar />
    <EditorLists :peerTeachers="peerTeachers" :labs="labs" />
  </div>
</template>

<script lang="ts">
import ActionBar from '@/components/ActionBar.vue';
import { defineComponent } from 'vue';
import EditorLists from '@/components/EditorLists.vue';
import Lab from '@/models/Lab';
import PeerTeacher from '@/models/PeerTeacher';

export default defineComponent({
  name: 'Editor',
  components: {
    ActionBar,
    EditorLists,
  },
  computed: {
    labs(): Lab[] {
      return Array.from(this.$store.state.labs.values()).sort((a, b) => a.id
        .localeCompare(b.id));
    },
    peerTeachers(): PeerTeacher[] {
      return Array.from(this.$store.state.peerTeachers.values()).sort((a, b) => a.lastname
        .toUpperCase().localeCompare(b.lastname.toUpperCase()));
    },
  },
});
</script>

<style>
#editor {
  display: flex;
  flex-direction: column;
  max-height: inherit;
}

#action-bar {
  flex-shrink: 0;
}
</style>

// src/components/Editor.svelte
<script lang="ts">
  import EditorActions from "./EditorActions.svelte";
  import EditorLists from "./EditorLists.svelte";
</script>

<div id="editor">
  <EditorActions />
  <EditorLists />
</div>

<style>
  #editor {
    display: flex;
    flex-direction: column;
  }

  :global(#action-bar) {
    flex-shrink: 0;
  }
</style>
